// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgxuqtsohaiqfkbgpuea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNneHVxdHNvaGFpcWZrYmdwdWVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MDgwMDIsImV4cCI6MjA2MTM4NDAwMn0.ywgJs0h3kFnYDXybTdRVoOiPZXk1Z13CE9JSteYqsbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);